version: '3'

services:
  hifi-gan-ja-dev:
    build: .
    container_name: hifi-gan-ja-dev
    image: hifi-gan-ja-dev-image
    shm_size: '24gb'
    tty: true
    volumes: 
      - /data/audio:/data
      - $PWD:/workspace
    command: '/bin/bash'
    ports:
      - 18281-18290:18281-18290
    #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]