seed: 3407

batch_size: 128
optim:
  learning_rate: 2e-4
  optimizer: AdamW
  weight_decay: 0
  optimizer_adam_beta1: 0.9
  optimizer_adam_beta2: 0.98
  clip_grad_norm: 1
  clip_grad_value: 0

epochs: 50