sample_rate: 16000
num_mel_bins: 80
hop_size: 256
win_size: 1024
fft_size: 1024
f_min: 0
f_max: 8000
f_max_loss: 8000 # sr / 2

train:
  waveform_length: 8192 # 8192, 25600
  validate_waveform_length: 16384 # 51200

aug:
  time_stretch: [0.9, 1.1, 0.5]
  volume_mul_params: [0,1, 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
  volume_aug_rate: 0


train_dataset_dir: /data/voc16k
val_dataset_dir: /data/voc16k_val